### ISSUE TITLE
Issue with French accent

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#1]
First of all, congratulation for your excellent application! :smile: 

I tried to generate a French sound pack for OpenTX 2.1
I got an annoying issue with the foreign accents
é è à ç ù
When the psv file is opened, all those characters are replaced with some unwanted symbol (see attached pic). So, I can't used your tool for now. Accent a very important, otherwise the pronunciation will be incorrect.
Is it possible to fix it? 
I attached an example psv file (ZIP archive).

![tmp](https://cloud.githubusercontent.com/assets/1685030/18315449/56dee32c-7517-11e6-855c-0638f2b6037b.png)

[OpenTX_2.1_Fr.psv.zip](https://github.com/CaffeineAU/TTSAutomate/files/459364/OpenTX_2.1_Fr.psv.zip)

**Comment by LapinFou** [comment]
I think, I found the origin of the problem.
Playing with Notepad++, I saw that the file is encoded in **UTF-8 without BOM** (UtF-8). If I convert the file on **UTF-8** format (UTF-8-BOM), then the file is properly loaded.  :smiling_imp: 
I hope this can help.

**Comment by CaffeineAU** [comment]
Thanks for your feedback. I load the PSV files assuming the encoding matches the operating system's current ANSI code page. (unless, as you identified, the file specifies a different encoding)

I'll investigate adding support for different encodings

**Comment by LapinFou** [comment]
OK. I'm glad you've been able to reproduce the issue.
With Notepad++, I got a good workaround. I love your tool. :+1:

**Comment by LapinFou** [comment]
Thanks !!!
I tried the version 2.7.0.1. Everything is working perfectly. :100:

**Comment by CaffeineAU** [comment]
Excellent, thanks for trying it out.
