### ISSUE TITLE
WAV Output format

### ISSUE THREAD

**Issue by PeterVRC** [CaffeineAU/TTSAutomate#10]
Could a 32KHz Wav file format be added?
This is used by the FRsky Taranis RC transmitter to play its speech files.

**Comment by CaffeineAU** [comment]
Hi Peter, I'll check to see if the resampler supports 32kHz. Thanks for the feedback!

**Comment by CaffeineAU** [comment]
Hi Peter, please try release [2.8.2.6](https://github.com/CaffeineAU/TTSAutomate/releases/tag/2.8.2.6)

**Comment by PeterVRC** [comment]
It outputs them at 32KHz - Audacity reports that.
So it looks like that is all fine.
I will try some files i the Taranis tonight.

Thanks a LOT for the VERY quick response!!!!!

**Comment by CaffeineAU** [comment]
No problem, Thanks for the suggestion.
