### ISSUE TITLE
Ivona Text To Speech not wokring anymore

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#18]
Hi Caffeine,

Ivona voices are not available anymore. Instead, I got this:
![tmp](https://user-images.githubusercontent.com/1685030/28406512-2d182d92-6d31-11e7-9e3e-05a38ae8e920.png)

**Comment by CaffeineAU** [comment]
Yes, it's listed as disabled on the status page as well, despite only using 10000 of the 50000 units so far this month. I'll investigate. Thanks for notifying me!

**Comment by CaffeineAU** [comment]
Ivona have stopped processing requests permanently now. I'll have to transition to Amazon Polly (which is a 'pay to play' service much sooner than I had anticipated :(

![ivona](https://user-images.githubusercontent.com/14083423/28655603-48cb1e3c-72e0-11e7-9304-3f7d13b757c3.png)

**Comment by LapinFou** [comment]
Shame... The voices were so great... 😠

**Comment by CaffeineAU** [comment]
I'm working on Amazon Polly integration now, there are are errors on their side with the sign up process which is making thing difficult though.

The voices should be similar

**Comment by LapinFou** [comment]
Great!!!
I hope you will make it work. Ivona, IMHO, are the best TTS engine.

**Comment by CaffeineAU** [comment]
Amazon Polly integration is up and running in [TTSAutomate 3.0.0.0](https://github.com/CaffeineAU/TTSAutomate/releases/tag/3.0.0.0)

**Comment by LapinFou** [comment]
I just tried. It works!!!!!
👍 👍 👍 👍 👍
