### ISSUE TITLE
[3.0.0.0] Voice field not properly refresh

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#19]
Hi,

When closing an opening again TTSAuto, the chosen voice is well memorize but the corresponding field is not refresh. Here is a snapshot:
![tmp](https://user-images.githubusercontent.com/1685030/28814401-b21c9d82-769d-11e7-8c6a-e71c271589c2.png)

Thanks again for such great tool. 😃

**Comment by CaffeineAU** [comment]
Hrmm, I thought I had squashed that bug! Thanks 😊

**Comment by CaffeineAU** [comment]
Ahh, I just realised you're using the software in French. I fixed the bug in the English resource files, but not the other languages! I'll fix that and re-upload the release.

**Comment by CaffeineAU** [comment]
I have updated the resource files. Please try it again.

**Comment by LapinFou** [comment]
I tried again. It is fixed. Thanks a lot.

**Comment by CaffeineAU** [comment]
Excellent, thanks for pointing it out and testing for me.

**Comment by LapinFou** [comment]
You're very welcome!!

**Comment by LapinFou** [comment]
By the way, maybe (when the French GUI is selected) it will be better to activate the voice announcement:
" [Voice xxx] Sélectionné" (French) instead "[Voice xxx] selected' (English).

**Comment by CaffeineAU** [comment]
That's an interesting idea. I'll see if I can implement something like that.Thanks!
