### ISSUE TITLE
Translation: French

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#2]
Here are some corrections:
Phrase Fichier → Fichier .PSV
Répertoire **de sortie** → Répertoire destination
**Folder** → Répertoire
**Filename** → Nom du fichier
**Phrase to Speak** → Phrase à prononcer
**Play** → Jouer
**Preview** → Aperçu
**Fichier Phrase Ouvrir** → Ouvrir fichier .PSV
Sélectionne**z** le répertoire de **sortie**... → Sélectionne**r** le répertoire de **destination...**
Créez un nouveau fichier **Phrase** → Créez un nouveau fichier **.PSV**
TTS **P**ournisseur → **F**ournisseur de moteurs TTS
Voix → Voix
Déplacer 1 ligne(s) **jusqu'à** → Déplacer 1 ligne(s) **vers le haut**
Déplacer 1 ligne(s) vers le bas → Déplacer 1 ligne(s) vers le bas
Insérer 1 lignes(s) **ci-dessus** → Insérer 1 lignes(s) **au-dessus**
Insérer 1 lignes(s) **ci-dessous** → Insérer 1 lignes(s) **en-dessous**
Jouer 1 **voix(s)** → Jouer 1 **fichier(s)**
Jouer **à tous** → Jouer **tous les fichiers**
Pause → Pause
CV → I didn't understand what is it for
Arrête**z** → Arrête**r**
Paramètres → Paramètres 
Enregistrer Phrase Fichier → Enregistrer le fichier .PSV
Enregistrer le fichier de phrase sous ... → Enregistrer une copie du fichier .PSV...
**Allez**! → Lancer!
Arrête**z**! → Arrête**r**!

**Comment by CaffeineAU** [comment]
Merci beaucoup Sebastien, I will update the tool with your translations.

Regards
Liam

**Comment by CaffeineAU** [comment]
I have updated the tool, with your translations (from release [2.5.1.0](https://github.com/CaffeineAU/TTSAutomate/releases/tag/2.5.1.0) onwards)

There are some strings in the tool that do not yet have translation support (headers in the datagrid such as Folder, Filename etc) so I'll look at implementing that.

**Comment by LapinFou** [comment]
Hi Liam,

Thanks a lot for taking in account my comments. :smile: 
I will check the new version ASAP.

**Comment by LapinFou** [comment]
I checked. This is much better. :100: 
Here are some others translations (I forgot the "Settings" panel):

**Main window:**
Répertoire destination → Répertoire **de** destination

Débit de parole → Débit de la parole
x-slow → Très lente
slow → Lente
medium → Normale
fast → Rapide
x-fast → Très rapide

Le volume → Volume
silent → Silence
x-soft → Très bas
soft → Bas
medium → Normal
loud → Fort
x-loud → Très fort

**Settings window**
_Option du programme_
Cadre prend effet sur le redémarrage du programme → Ces modifications prendront effet lors du prochain redémarrage du programme
Re-ouvrir le fichier PSV dernière → Lancer avec le dernier fichier PSV ouvert
Configurer répertoire de sortie au dernier répertoire de sortie → Mémoriser le dernier répertoire de destination choisi
Copier dossier précédent lors de l'insertion des lignes → Copier le précédent dossier lors de l'insertion des lignes
Copier dossier précédent lors de la sélection ligne vide → Copier le précédent dossier lors de la sélection de lignes vides

_Options vocales_
Rappelez-vous les paramètres de langue → Se souvenir des paramètres de langue choisis
Encode MP3 au WAV → Encoder MP3 en WAV

**Comment by CaffeineAU** [comment]
Unfortunately I can't yet translate the strings for speed and volume, as they are the values that get passed to the TTS engine.

I'll see about implementing an abstraction so that they displayed string can be translated.

**Comment by LapinFou** [comment]
OK. Don't worry, even for a normal French guy, it is easy to understand. At least, you got the correct translation for the "Settings" panel. :wink:

**Comment by CaffeineAU** [comment]
Hi Sebastien, 

I have incorporated your new translations. Some of the text doesn't fit properly so I'll adjust sizing in the next update.

**Comment by LapinFou** [comment]
OK. I'll check. Maybe I may shorten some texts. French language is very "verbose"...

**Comment by LapinFou** [comment]
OK. Here are few update:
**Main window:**
Sélectionner le répertoire de destination... → Choisir répertoire de destination...

This should fit well. :smile: 

**Settings window**
_Options vocales_
Encode MP3 au WAV → Encode**r** MP3 en WAV

**Comment by LapinFou** [comment]
I tried the latest 2.7.0.1 version, still few French translation issue:
**Settings window**
_Options vocales_
Encode MP3 au WAV → Encode**r** MP3 en WAV

**Main window**
_Open file options_
Ouvrir comme l'encodage par défaut → Ouvrir avec l'encodage par défaut 
Ouvrir l'encodage XXXX → Ouvrir avec l'encodage XXXX

Thanks again for this nice tool. Looks like you got some (well deserved) success on the RCGroups forum.

**Comment by CaffeineAU** [comment]
Thanks Sebastien, I have updated the 2.7.0.1 release with your translations.

**Comment by LapinFou** [comment]
I checked the translation, it is OK except one point.  There is still a misssing **R** at the end of the word **ENCODE** in the setting window. :wink: 
Encode MP3 au WAV → Encode**R** MP3 en WAV

**Comment by LapinFou** [comment]
When this correction is done, you may close this ticket.

**Comment by CaffeineAU** [comment]
Haha I've been looking at that every time you mention it thinking 'I've changed it to Encode MP3 **en** WAV already'

**Comment by LapinFou** [comment]
I should have been more precise. My mistake. :smile:

**Comment by CaffeineAU** [comment]
Finally fixed! Thank for your assistance 🎉

**Comment by LapinFou** [comment]
You're welcome. Thanks for your tool. :+1:
