### ISSUE TITLE
TTSAutomate for OSX?

### ISSUE THREAD

**Issue by Soarer66** [CaffeineAU/TTSAutomate#26]
Is there any likelihood that this very useful App will be ported to OSX?

**Comment by CaffeineAU** [comment]
No unfortunately. I investigated porting it across to OSX and Linux, however there are a number of features and libraries that I use in the code that are not supported.

There is a similar tool for OSX, I can't remember the name and I have no means of trying out the various options to see if it's the one I remember, however these may be a good start: https://github.com/RCdiy/OpenTXSounds & http://rcdiy.ca/create-voice-tracks-mac/
