### ISSUE TITLE
[Bug] Move/Insert number of lines not correct in French

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#3]
On the snapshot below, you will see than only 1 field is displaying the correct number of selected lines.
It is working fine for the English version.

![tmp](https://cloud.githubusercontent.com/assets/1685030/18341382/0457a542-75aa-11e6-8193-4b51cca9f0fa.png)

**Comment by CaffeineAU** [comment]
Thanks Sebastien.

**Comment by CaffeineAU** [comment]
Hi Sebastien, resolved and updated the 2.5.1.0 release.
