### ISSUE TITLE
[2.7.1.0]French translation

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#4]
Hi !
:smile: 
In the setting panel:
Longueur limite filename a xxx caractères → Nom limité à xxx caractères
**or if you've got enough room:**
Longueur limite filename a xxx caractères → Nom du fichier limité à xxx caractères

**Comment by CaffeineAU** [comment]
Thanks again!

**Comment by LapinFou** [comment]
You're very welcome. Thanks to you for this great tool. :+1:

**Comment by CaffeineAU** [comment]
I have updated the [2.7.10](https://github.com/CaffeineAU/TTSAutomate/releases/tag/2.7.1.0) release with your translation.

Thanks again :grinning:

**Comment by LapinFou** [comment]
I checked. It is OK.
Thanks for your work.

**Comment by CaffeineAU** [comment]
Thanks!
