### ISSUE TITLE
[2.8.1.0]French translation

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#5]
Bonjour ! :smile: 

Again, here is a translation correction. :wink: 
Vérifiez nouvelle version du logiciel au démarrage → Vérifiez la présence d'une mise à jour au démarrage

**Comment by CaffeineAU** [comment]
Thanks Sebastien, I'll update the translation when i fix the issue with
scrollbar visibility on the list of phrases.

**Comment by CaffeineAU** [comment]
Updated translation in 2.8.1.1

**Comment by LapinFou** [comment]
Hi Caffeine,

Here is one more:
Une nouvelle version est disponible. Cliquez ici si vous souhaitez aller à télécharger → Une nouvelle version est disponible. Cliquez ici pour la télécharger...

**[EDIT]** Oups the correction given below is not completely correct. The Z should be a R (word Vérifier).
Vérifiez la présence d'une mise à jour au démarrage → Vérifie**r** la présence d'une mise à jour au démarrage

**Comment by CaffeineAU** [comment]
Updated translation in [2.8.1.2](https://github.com/CaffeineAU/TTSAutomate/releases/tag/2.8.1.2)

**Comment by LapinFou** [comment]
It is al good. Thanks Caffeine. 👍
