### ISSUE TITLE
[2.8.2.0]French issue

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#6]
Hi Caffeine,

2 issues with the French pack.
First, a display issue (in red):
![tmp](https://cloud.githubusercontent.com/assets/1685030/19727595/52bbfba0-9b90-11e6-928c-4db08b914244.png)
There are two options: you can change the windows size or you can replace "**Choisir répertoire de destination...**" with "**Répertoire de destination...**".

Second issue, "**répertoire de sortie Ouvrir dans l'Explorateur Windows**" should be "**Ouvrir le répertoire de destination dans l'Explorateur de fichiers**".

**Comment by CaffeineAU** [comment]
Thanks Sebastien, I'll incorporate your changes.

**Comment by LapinFou** [comment]
Tahnks! 😄

**Comment by CaffeineAU** [comment]
Changes incorporated in to release [2.8.2.1](https://github.com/CaffeineAU/TTSAutomate/releases/tag/2.8.2.1)

**Comment by LapinFou** [comment]
Thanks!
