### ISSUE TITLE
Issue with "Microsoft Windows Text To Speech"

### ISSUE THREAD

**Issue by LapinFou** [CaffeineAU/TTSAutomate#8]
Hi Caffeine,

Something is broken since (at least) version 2.7.0.1:
Despite the selected voice under "Microsoft Windows Text To Speech", it is always the Zira voice which is used.

![tmp](https://cloud.githubusercontent.com/assets/1685030/20097219/9d49863e-a5ad-11e6-8040-c5c2b64f5bd6.png)

I will check on my personal PC at home tonight. Just to be sure, that nothing is broken on my professional laptop (the one I used to test).

**Comment by LapinFou** [comment]
Hi Caffeine,

I confirm the problem. Same issue on my laptop at home.
It was definitely working on the first version. Since, I concentrated on using Ivona, I didn't check if this one was working well on the latest versions.

**Comment by CaffeineAU** [comment]
It's to do with the changes to support SSML. I've resolved the issue and will upload it shortly as [2.8.2.3](https://github.com/CaffeineAU/TTSAutomate/releases/tag/2.8.2.3)

**Comment by LapinFou** [comment]
It does work. Thanks for this quick fix. 👍
